version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitor-net

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
